version: "3.3"
services:
  db:
    restart: always
    image: postgres:15.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=web
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  app :
    depends_on:
      - db
    build: web
    ports:
      - 1717:1717
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=web